quadrantChart
    title Reach and engagement of snake games
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Python Snake Game": [0.3, 0.6]
    "Classic Snake Game": [0.45, 0.23]
    "Snake Xenzia": [0.57, 0.69]
    "Snake.io": [0.78, 0.34]
    "Snake '97": [0.40, 0.34]
    "Snake vs Block": [0.35, 0.78]
    "Snakebird": [0.5, 0.6]
    "Our Target Product": [0.6, 0.7]
