quadrantChart
    title Reach and engagement of photo-sharing apps
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Instagram": [0.9, 0.9]
    "Snapchat": [0.8, 0.7]
    "Pinterest": [0.7, 0.6]
    "VSCO": [0.6, 0.8]
    "500px": [0.5, 0.5]
    "Flickr": [0.4, 0.4]
    "EyeEm": [0.3, 0.6]
    "Our Target Product": [0.7, 0.8]
