quadrantChart
    title Reach and engagement of survey apps
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Wevox": [0.6, 0.7]
    "SurveyMonkey": [0.4, 0.8]
    "Typeform": [0.7, 0.6]
    "Google Forms": [0.8, 0.4]
    "Qualtrics": [0.5, 0.9]
    "Zoho Survey": [0.6, 0.5]
    "SurveyGizmo": [0.4, 0.6]
    "Our Target Product": [0.6, 0.7]
