quadrantChart
    title Reach and engagement of plant watering apps
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Plant Watering App": [0.3, 0.6]
    "Garden Care App": [0.45, 0.23]
    "Weather-based Plant Watering App": [0.57, 0.69]
    "Plant Care Assistant": [0.78, 0.34]
    "Smart Plant Watering System": [0.40, 0.34]
    "Plant Care Tracker": [0.35, 0.78]
    "Indoor Plant Care App": [0.6, 0.7]
    "Our Target Product": [0.5, 0.6]
